language: python
python:
  - "2.7"
#  - "3.4"
#  - "3.2"
#  - "3.4"
#  - "3.5"
#  - "nightly" # currently points to 3.6-dev
#  - "pypy"
#  - "3.2"
#  - "3.3"
#  - "3.4"
#  - "3.5"
#  - "nightly" # currently points to 3.6-dev
#  - "pypy"
# command to install dependencies
install:
# - pip install .
 - pip install -r requirements.txt
# command to run tests
script: nosetests
# script: py.test -s --verbose --doctest-modules chpyu
