language: python

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3

install:
  - pip install tox
  - pip install coveralls
  - pip install -r requirements.txt

before_script:
  - tox -e cov-init
script:
  - tox -e $TOXENV
before_deploy_script:
  - tox -e cov-report
  - coveralls
