language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

install:
 - pip install -r requirements.txt

script: nosetests
# script: py.test -s --verbose --doctest-modules chpyu
